{"name": "test_change_user_name", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 5", "trace": "@pytest.mark.regression\n    def test_change_user_name():\n>       assert 4 == 5\nE       assert 4 == 5\n\ntests/something2_test.py:58: AssertionError"}, "start": 1725260753646, "stop": 1725260753646, "uuid": "2203c374-f1a2-416c-834b-55453cfd5ddc", "historyId": "c259cb851892b66effed72ec816a4e14", "testCaseId": "c259cb851892b66effed72ec816a4e14", "fullName": "tests.something2_test#test_change_user_name", "labels": [{"name": "tag", "value": "regression"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "something2_test"}, {"name": "host", "value": "MS105M.local"}, {"name": "thread", "value": "7097-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.something2_test"}]}