{"name": "test_change_user_name", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 5", "trace": "@pytest.mark.regression\n    def test_change_user_name():\n>       assert 4 == 5\nE       assert 4 == 5\n\ntests/something2_test.py:56: AssertionError"}, "start": 1725082832224, "stop": 1725082832225, "uuid": "e8169a4d-01ea-48aa-8d98-eb147e314ada", "historyId": "c259cb851892b66effed72ec816a4e14", "testCaseId": "c259cb851892b66effed72ec816a4e14", "fullName": "tests.something2_test#test_change_user_name", "labels": [{"name": "tag", "value": "regression"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "something2_test"}, {"name": "host", "value": "MS105M.local"}, {"name": "thread", "value": "1581-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.something2_test"}]}